### ISSUE TITLE
Do not depend on external resource for version checking

### ISSUE THREAD

**Issue by jose1711** [LethalEthan/Bluetooth-Unlock#10]
https://github.com/LethalEthan/Bluetooth-Unlock/blob/8041e91e53c5367e95862ff700e1e47e860b7cfa/Bluetooth-Unlock.py#L45

If you think people are happy to see scripts downloading external resources (be it just a small text file) from unknown resources, then think again. One approach would be
 * drop dependency on wget (replace it with python requests)
 * be more transparent (use github).

Checkout out this example:
```
import requests
..
..
r = requests.get('https://github.com/LethalEthan/Bluetooth-Unlock/releases/latest')
latest_version = r.url.split('/')[-1]  # BU-V1RC6
```

**Comment by LethalEthan** [comment]
The reason downloading from my own server is that I can modify it at ease, and make updates straight  away. Using github wouldn't really work since I would need to  make a file commit every time which is a bit tedious. I will put a "Downloading from: ecloud". Or something similar. note ecloud is my own cloud server running nextcloud

**Comment by jose1711** [comment]
Not sure what's the planned frequency of updates but as a user I want to have a full control whether the script is checking for an update and also if it is going to download something from the internet. Plus private nextcloud instance does not mean it is unbreakable and/or unhackable.

**Comment by LethalEthan** [comment]
I totally understand I will add a would you like to check for updates option, I know it's not unbreakable and unhackable it's because it's an easy and convenient way of doing it.
