### ISSUE TITLE
POP! Os

### ISSUE THREAD

**Issue by jhalmu** [LethalEthan/Bluetooth-Unlock#24]
Can we have Pop OS in supported OS.

Btw stucking in 

Searching for nearby devices...

[] 

Enter Bluetooth Address of the device (e.g AA:BB:CC:DD:EE:FF):

**Comment by LethalEthan** [comment]
Hi there, I personally use pop-os aswell so it should work, unless there were missing dependencies. Although I've said the project is no longer maintained I will make an exceptition as I've found a bug that the config gets messed up due to me using append instead of write (derp). I will also amend the install.sh to include pop-os.

**Comment by jhalmu** [comment]
Updated and installation works, thanks. Now waiting for sleep (pun intended).

**Comment by jhalmu** [comment]
Is it intended, that program stays open in terminal? How long away I should be from pc where it its running? Do Do not sleep -programs (caffeine etc) interruput working? How if I stop bluetooth from my phone, does that mean that that lock down machine?
I will test this of course, but haven't yet noticed lockings.
p.s pun did not succeed: not sleep but lock :/ :)

**Comment by jhalmu** [comment]
Ok, did not lock out/off. Need read the manual.

**Comment by LethalEthan** [comment]
Since this is very simple script it does just stay in the terminal, though you can install screen and run it and close the terminal after. There maybe a Bluetooth-Unlock V2 in the future that will be able to run in the background, have a GUI and perhaps an android app, but I have college at the moment and I'm working on another project that's more important to me so I don't really have the time to work on it. As soon as the Bluetooth connection is lost it waits a few seconds and then locks, caffeine should not affect it. If you cannot recover the Bluetooth connection you can still unlock your PC and you won't be locked out because it only runs the locking sequence once. For GNOME it does require gnome-screensaver to be installed so if it doesn't lock even after you install it please get back to me.
