### ISSUE TITLE
did not find my phone

### ISSUE THREAD

**Issue by JPMHb** [LethalEthan/Bluetooth-Unlock#27]
**Describe the bug**
my phone was on and connected yet when the software scanned it found two other devices and not my phone.  I manually added my phone MAC address and all is working fine!  Just would have been nice had the software found it

**To Reproduce**
I suspect you would need my phone and my laptop

**Expected behaviour**
see above

**Screenshots**

**Desktop (please complete the following information):**
Ubunto 20.4 GNOME

**Additional context**

**Comment by LethalEthan** [comment]
Hi, there unfortunately BU-V1 is only receiving security/OS support updates, BU-V2 is being made but is not my main priority due to college taking most of my time. I totally agree that it should have picked up the device but since their are many factors why this may have happened and BU-V1 not really being the best in design I won't be looking to fix this and you can expect BU-V2 to be better built and more reliable in the future. Kind Regards, Ethan.
